services:
  - type: web
    name: learnpath-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm rebuild sqlite3 --build-from-source
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: DB_PATH
        value: ./learnpath.sqlite

      - key: CORS_ORIGIN
        value: https://learnpath-snowy.vercel.app,https://myapp-gyd2bqbye-geetha-123.vercel.app

      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRES_IN
        value: 7d
